# Generated by Django 5.0.4 on 2024-11-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_forum_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='accounts.forum'),
        ),
    ]
