# Generated by Django 5.0.4 on 2024-11-02 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_mensagem_conteudo_alter_mensagem_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
