# Generated by Django 5.0.4 on 2024-11-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mensagem_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
